import type {
  EffectivenessCriteria,
  FrameworkComponent,
  MaterialControl,
  Risk,
  Control,
  TestPlan,
  Issue,
  IntegrationStatus,
  ControlGap,
  ApprovalWorkflow,
  DashboardData,
} from '@/types';

export const mockEffectivenessCriteria: EffectivenessCriteria[] = [
  {
    id: 'ec-1',
    dimension: 'Design',
    criteria: 'Controls are appropriately designed to address identified risks',
    threshold: '100% of material controls have documented design rationale',
    evidenceType: ['Design documentation', 'Risk-control matrices'],
    frequency: 'annual',
    status: 'approved',
    approvedBy: 'John Smith',
    approvedDate: '2024-01-15',
  },
  {
    id: 'ec-2',
    dimension: 'Implementation',
    criteria: 'Controls are consistently implemented as designed',
    threshold: '95% implementation rate across all material controls',
    evidenceType: ['Test results', 'Evidence logs'],
    frequency: 'quarterly',
    status: 'approved',
    approvedBy: 'John Smith',
    approvedDate: '2024-01-15',
  },
  {
    id: 'ec-3',
    dimension: 'Operation',
    criteria: 'Controls operate effectively throughout the period',
    threshold: 'No critical exceptions; <5% high-severity exceptions',
    evidenceType: ['Continuous monitoring alerts', 'Exception reports'],
    frequency: 'continuous',
    status: 'approved',
    approvedBy: 'John Smith',
    approvedDate: '2024-01-15',
  },
  {
    id: 'ec-4',
    dimension: 'Decision-Use',
    criteria: 'Control outputs inform business decisions',
    threshold: 'Evidence of control data in decision-making processes',
    evidenceType: ['Meeting minutes', 'Decision logs'],
    frequency: 'quarterly',
    status: 'in_review',
  },
];

export const mockFrameworkComponents: FrameworkComponent[] = [
  {
    id: 'fc-1',
    type: 'governance',
    name: 'Risk Committee Structure',
    description: 'Board-level and executive committees with clear decision rights',
    owner: 'Chief Risk Officer',
    status: 'approved',
    lastReviewed: '2024-01-10',
  },
  {
    id: 'fc-2',
    type: 'risk_taxonomy',
    name: 'Enterprise Risk Taxonomy',
    description: 'Standardized risk categories aligned to strategic objectives',
    owner: 'Risk Management Team',
    status: 'approved',
    lastReviewed: '2024-01-05',
  },
  {
    id: 'fc-3',
    type: 'risk_appetite',
    name: 'Risk Appetite Framework',
    description: 'Board-approved risk appetite statements with tolerances and triggers',
    owner: 'Chief Risk Officer',
    status: 'approved',
    lastReviewed: '2023-12-20',
  },
  {
    id: 'fc-4',
    type: 'three_lines',
    name: 'Three Lines of Defence Model',
    description: 'RACI matrix and assurance mapping across business, risk, and audit',
    owner: 'Chief Audit Executive',
    status: 'in_review',
  },
];

export const mockMaterialControls: MaterialControl[] = [
  {
    id: 'mc-1',
    name: 'Segregation of Duties - Payments',
    description: 'Separation between payment initiator and approver roles',
    materialityScore: 92,
    rationale: 'Critical for fraud prevention; regulatory requirement; high financial exposure',
    owner: 'Finance Director',
    evidenceSource: 'ERP system logs',
    testingFrequency: 'Quarterly',
    dependencies: ['ERP', 'IAM'],
    effectiveness: 'effective',
    lastTested: '2024-01-20',
  },
  {
    id: 'mc-2',
    name: 'Access Control - Financial Systems',
    description: 'Role-based access controls for financial reporting systems',
    materialityScore: 88,
    rationale: 'Material to financial statement integrity; SOX requirement',
    owner: 'IT Security Manager',
    evidenceSource: 'Azure AD logs',
    testingFrequency: 'Quarterly',
    dependencies: ['Azure AD', 'ERP'],
    effectiveness: 'effective',
    lastTested: '2024-01-18',
  },
  {
    id: 'mc-3',
    name: 'Vendor Due Diligence',
    description: 'Risk assessment before vendor onboarding',
    materialityScore: 76,
    rationale: 'Prevents supply chain disruption; compliance requirement',
    owner: 'Procurement Head',
    evidenceSource: 'Vendor management system',
    testingFrequency: 'Annual',
    dependencies: ['Vendor Portal'],
    effectiveness: 'partially_effective',
    lastTested: '2023-11-15',
  },
  {
    id: 'mc-4',
    name: 'Data Backup & Recovery',
    description: 'Automated daily backups with quarterly recovery testing',
    materialityScore: 85,
    rationale: 'Business continuity; data protection regulation',
    owner: 'IT Operations Manager',
    evidenceSource: 'Backup logs',
    testingFrequency: 'Quarterly',
    dependencies: ['Backup System'],
    effectiveness: 'effective',
    lastTested: '2024-01-25',
  },
];

export const mockRisks: Risk[] = [
  {
    id: 'r-1',
    title: 'Unauthorized Payment Processing',
    description: 'Risk of fraudulent or erroneous payments being processed',
    category: 'Financial',
    inherentRisk: 'high',
    residualRisk: 'low',
    owner: 'CFO',
    linkedObjectives: ['Financial Integrity', 'Fraud Prevention'],
    linkedControls: ['mc-1'],
    lastAssessed: '2024-01-15',
  },
  {
    id: 'r-2',
    title: 'Data Breach',
    description: 'Unauthorized access to sensitive customer or financial data',
    category: 'Cybersecurity',
    inherentRisk: 'critical',
    residualRisk: 'medium',
    owner: 'CTO',
    linkedObjectives: ['Data Protection', 'Regulatory Compliance'],
    linkedControls: ['mc-2'],
    lastAssessed: '2024-01-20',
  },
  {
    id: 'r-3',
    title: 'Supply Chain Disruption',
    description: 'Failure of critical vendors impacting operations',
    category: 'Operational',
    inherentRisk: 'high',
    residualRisk: 'medium',
    owner: 'COO',
    linkedObjectives: ['Business Continuity', 'Operational Efficiency'],
    linkedControls: ['mc-3'],
    lastAssessed: '2024-01-10',
  },
];

export const mockControls: Control[] = [
  {
    id: 'c-1',
    name: 'Two-Factor Authentication',
    description: 'MFA required for all system access',
    type: 'preventive',
    automation: 'automated',
    frequency: 'Real-time',
    owner: 'IT Security',
    linkedRisks: ['r-2'],
    effectiveness: 'effective',
    evidenceSource: 'Azure AD',
  },
  {
    id: 'c-2',
    name: 'Monthly Reconciliation Review',
    description: 'Management review of account reconciliations',
    type: 'detective',
    automation: 'manual',
    frequency: 'Monthly',
    owner: 'Finance Manager',
    linkedRisks: ['r-1'],
    effectiveness: 'effective',
    evidenceSource: 'Reconciliation system',
  },
  {
    id: 'c-3',
    name: 'Incident Response Protocol',
    description: 'Documented procedures for security incident response',
    type: 'corrective',
    automation: 'manual',
    frequency: 'As needed',
    owner: 'Security Team',
    linkedRisks: ['r-2'],
    effectiveness: 'effective',
    evidenceSource: 'SIEM',
  },
];

export const mockTestPlans: TestPlan[] = [
  {
    id: 'tp-1',
    controlId: 'mc-1',
    controlName: 'Segregation of Duties - Payments',
    testType: 'operating',
    tester: 'Internal Audit',
    scheduledDate: '2024-04-15',
    status: 'not_started',
    remediationRequired: false,
  },
  {
    id: 'tp-2',
    controlId: 'mc-2',
    controlName: 'Access Control - Financial Systems',
    testType: 'operating',
    tester: 'IT Audit',
    scheduledDate: '2024-04-10',
    status: 'in_progress',
    remediationRequired: false,
  },
  {
    id: 'tp-3',
    controlId: 'mc-3',
    controlName: 'Vendor Due Diligence',
    testType: 'design',
    tester: 'Compliance Team',
    scheduledDate: '2024-03-20',
    status: 'completed',
    results: 'Control design is adequate but implementation has gaps',
    exceptions: ['Missing due diligence for 3 vendors onboarded in Q4'],
    remediationRequired: true,
  },
];

export const mockIssues: Issue[] = [
  {
    id: 'i-1',
    title: 'Incomplete Vendor Due Diligence',
    description: 'Three vendors onboarded without full risk assessment',
    severity: 'high',
    controlId: 'mc-3',
    discoveredDate: '2024-01-25',
    status: 'in_remediation',
    owner: 'Procurement Head',
    dueDate: '2024-03-15',
    remediationPlan: 'Complete retroactive due diligence; update onboarding process',
    retestDate: '2024-03-20',
  },
  {
    id: 'i-2',
    title: 'Segregation of Duties Exception',
    description: 'One user had both initiation and approval rights for 2 weeks',
    severity: 'medium',
    controlId: 'mc-1',
    discoveredDate: '2024-01-15',
    status: 'closed',
    owner: 'Finance Director',
    dueDate: '2024-01-30',
    remediationPlan: 'Access revoked; process updated to prevent recurrence',
  },
  {
    id: 'i-3',
    title: 'Backup Recovery Test Failed',
    description: 'One database failed recovery test due to corruption',
    severity: 'critical',
    controlId: 'mc-4',
    discoveredDate: '2024-02-01',
    status: 'open',
    owner: 'IT Operations Manager',
    dueDate: '2024-02-10',
  },
];

export const mockIntegrations: IntegrationStatus[] = [
  {
    id: 'int-1',
    system: 'SAP ERP',
    status: 'connected',
    lastSync: '2024-02-04T09:30:00',
    signalsReceived: 15234,
    exceptionsRaised: 12,
  },
  {
    id: 'int-2',
    system: 'Azure Active Directory',
    status: 'connected',
    lastSync: '2024-02-04T09:45:00',
    signalsReceived: 8921,
    exceptionsRaised: 3,
  },
  {
    id: 'int-3',
    system: 'ServiceNow',
    status: 'connected',
    lastSync: '2024-02-04T09:20:00',
    signalsReceived: 4532,
    exceptionsRaised: 7,
  },
  {
    id: 'int-4',
    system: 'Vendor Portal',
    status: 'error',
    lastSync: '2024-02-03T14:20:00',
    signalsReceived: 0,
    exceptionsRaised: 0,
  },
];

export const mockControlGaps: ControlGap[] = [
  {
    id: 'cg-1',
    source: 'external',
    title: 'New GDPR Enforcement Guidance',
    description: 'EU regulator issued new guidance on data retention requiring enhanced controls',
    affectedControls: ['mc-2'],
    riskTheme: 'Data Privacy',
    priority: 'high',
    proposedAction: 'Implement automated data retention policy enforcement',
    status: 'pending',
    identifiedDate: '2024-01-28',
  },
  {
    id: 'cg-2',
    source: 'internal',
    title: 'Repeated Reconciliation Exceptions',
    description: 'Same account showing exceptions for 3 consecutive months',
    affectedControls: ['c-2'],
    riskTheme: 'Financial Accuracy',
    priority: 'medium',
    proposedAction: 'Review and update reconciliation control; consider automation',
    status: 'in_review',
    identifiedDate: '2024-01-20',
  },
  {
    id: 'cg-3',
    source: 'external',
    title: 'Industry Ransomware Trend',
    description: 'Increased ransomware attacks in sector; peer company impacted',
    affectedControls: ['mc-4', 'c-3'],
    riskTheme: 'Cybersecurity',
    priority: 'critical',
    proposedAction: 'Enhance backup encryption; implement network segmentation',
    status: 'approved',
    identifiedDate: '2024-02-01',
  },
];

export const mockApprovals: ApprovalWorkflow[] = [
  {
    id: 'app-1',
    itemType: 'Effectiveness Criteria',
    itemId: 'ec-4',
    itemName: 'Decision-Use Criteria',
    requester: 'Risk Manager',
    currentApprover: 'Audit Committee Chair',
    status: 'pending',
    submittedDate: '2024-02-01',
  },
  {
    id: 'app-2',
    itemType: 'Framework Component',
    itemId: 'fc-4',
    itemName: 'Three Lines of Defence Model',
    requester: 'Chief Audit Executive',
    currentApprover: 'Board',
    status: 'pending',
    submittedDate: '2024-01-30',
  },
  {
    id: 'app-3',
    itemType: 'Control Gap',
    itemId: 'cg-2',
    itemName: 'Repeated Reconciliation Exceptions',
    requester: 'Finance Director',
    currentApprover: '2nd Line Review',
    status: 'in_review',
    submittedDate: '2024-01-25',
    comments: 'Need more detail on proposed automation approach',
  },
];

export const mockDashboardData: DashboardData = {
  effectivenessStatus: {
    met: 8,
    partially: 2,
    notMet: 1,
  },
  controlHealth: {
    tested: 42,
    effective: 38,
    totalMaterial: 45,
  },
  issuesByTheme: [
    { theme: 'Cybersecurity', count: 5 },
    { theme: 'Financial Controls', count: 3 },
    { theme: 'Vendor Management', count: 2 },
    { theme: 'Data Privacy', count: 4 },
    { theme: 'Access Management', count: 2 },
  ],
  remediationProgress: [
    { month: 'Sep', opened: 8, closed: 6 },
    { month: 'Oct', opened: 12, closed: 10 },
    { month: 'Nov', opened: 7, closed: 9 },
    { month: 'Dec', opened: 10, closed: 8 },
    { month: 'Jan', opened: 9, closed: 11 },
    { month: 'Feb', opened: 5, closed: 3 },
  ],
};

export const mockApiService = {
  getEffectivenessCriteria: () => Promise.resolve(mockEffectivenessCriteria),
  getFrameworkComponents: () => Promise.resolve(mockFrameworkComponents),
  getMaterialControls: () => Promise.resolve(mockMaterialControls),
  getRisks: () => Promise.resolve(mockRisks),
  getControls: () => Promise.resolve(mockControls),
  getTestPlans: () => Promise.resolve(mockTestPlans),
  getIssues: () => Promise.resolve(mockIssues),
  getIntegrations: () => Promise.resolve(mockIntegrations),
  getControlGaps: () => Promise.resolve(mockControlGaps),
  getApprovals: () => Promise.resolve(mockApprovals),
  getDashboardData: () => Promise.resolve(mockDashboardData),
};
